// source: options.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.grakn.protocol.Options', null, global);
goog.exportSymbol('proto.grakn.protocol.Options.BatchSizeOptCase', null, global);
goog.exportSymbol('proto.grakn.protocol.Options.ExplainOptCase', null, global);
goog.exportSymbol('proto.grakn.protocol.Options.InferOptCase', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.grakn.protocol.Options = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.grakn.protocol.Options.oneofGroups_);
};
goog.inherits(proto.grakn.protocol.Options, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.grakn.protocol.Options.displayName = 'proto.grakn.protocol.Options';
}

/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.grakn.protocol.Options.oneofGroups_ = [[1],[2],[3]];

/**
 * @enum {number}
 */
proto.grakn.protocol.Options.InferOptCase = {
  INFER_OPT_NOT_SET: 0,
  INFER: 1
};

/**
 * @return {proto.grakn.protocol.Options.InferOptCase}
 */
proto.grakn.protocol.Options.prototype.getInferOptCase = function() {
  return /** @type {proto.grakn.protocol.Options.InferOptCase} */(jspb.Message.computeOneofCase(this, proto.grakn.protocol.Options.oneofGroups_[0]));
};

/**
 * @enum {number}
 */
proto.grakn.protocol.Options.ExplainOptCase = {
  EXPLAIN_OPT_NOT_SET: 0,
  EXPLAIN: 2
};

/**
 * @return {proto.grakn.protocol.Options.ExplainOptCase}
 */
proto.grakn.protocol.Options.prototype.getExplainOptCase = function() {
  return /** @type {proto.grakn.protocol.Options.ExplainOptCase} */(jspb.Message.computeOneofCase(this, proto.grakn.protocol.Options.oneofGroups_[1]));
};

/**
 * @enum {number}
 */
proto.grakn.protocol.Options.BatchSizeOptCase = {
  BATCH_SIZE_OPT_NOT_SET: 0,
  BATCH_SIZE: 3
};

/**
 * @return {proto.grakn.protocol.Options.BatchSizeOptCase}
 */
proto.grakn.protocol.Options.prototype.getBatchSizeOptCase = function() {
  return /** @type {proto.grakn.protocol.Options.BatchSizeOptCase} */(jspb.Message.computeOneofCase(this, proto.grakn.protocol.Options.oneofGroups_[2]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.grakn.protocol.Options.prototype.toObject = function(opt_includeInstance) {
  return proto.grakn.protocol.Options.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.grakn.protocol.Options} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.grakn.protocol.Options.toObject = function(includeInstance, msg) {
  var f, obj = {
    infer: jspb.Message.getBooleanFieldWithDefault(msg, 1, false),
    explain: jspb.Message.getBooleanFieldWithDefault(msg, 2, false),
    batchSize: jspb.Message.getFieldWithDefault(msg, 3, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.grakn.protocol.Options}
 */
proto.grakn.protocol.Options.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.grakn.protocol.Options;
  return proto.grakn.protocol.Options.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.grakn.protocol.Options} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.grakn.protocol.Options}
 */
proto.grakn.protocol.Options.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setInfer(value);
      break;
    case 2:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setExplain(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setBatchSize(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.grakn.protocol.Options.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.grakn.protocol.Options.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.grakn.protocol.Options} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.grakn.protocol.Options.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = /** @type {boolean} */ (jspb.Message.getField(message, 1));
  if (f != null) {
    writer.writeBool(
      1,
      f
    );
  }
  f = /** @type {boolean} */ (jspb.Message.getField(message, 2));
  if (f != null) {
    writer.writeBool(
      2,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 3));
  if (f != null) {
    writer.writeInt32(
      3,
      f
    );
  }
};


/**
 * optional bool infer = 1;
 * @return {boolean}
 */
proto.grakn.protocol.Options.prototype.getInfer = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 1, false));
};


/**
 * @param {boolean} value
 * @return {!proto.grakn.protocol.Options} returns this
 */
proto.grakn.protocol.Options.prototype.setInfer = function(value) {
  return jspb.Message.setOneofField(this, 1, proto.grakn.protocol.Options.oneofGroups_[0], value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.grakn.protocol.Options} returns this
 */
proto.grakn.protocol.Options.prototype.clearInfer = function() {
  return jspb.Message.setOneofField(this, 1, proto.grakn.protocol.Options.oneofGroups_[0], undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.grakn.protocol.Options.prototype.hasInfer = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional bool explain = 2;
 * @return {boolean}
 */
proto.grakn.protocol.Options.prototype.getExplain = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 2, false));
};


/**
 * @param {boolean} value
 * @return {!proto.grakn.protocol.Options} returns this
 */
proto.grakn.protocol.Options.prototype.setExplain = function(value) {
  return jspb.Message.setOneofField(this, 2, proto.grakn.protocol.Options.oneofGroups_[1], value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.grakn.protocol.Options} returns this
 */
proto.grakn.protocol.Options.prototype.clearExplain = function() {
  return jspb.Message.setOneofField(this, 2, proto.grakn.protocol.Options.oneofGroups_[1], undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.grakn.protocol.Options.prototype.hasExplain = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional int32 batch_size = 3;
 * @return {number}
 */
proto.grakn.protocol.Options.prototype.getBatchSize = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.grakn.protocol.Options} returns this
 */
proto.grakn.protocol.Options.prototype.setBatchSize = function(value) {
  return jspb.Message.setOneofField(this, 3, proto.grakn.protocol.Options.oneofGroups_[2], value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.grakn.protocol.Options} returns this
 */
proto.grakn.protocol.Options.prototype.clearBatchSize = function() {
  return jspb.Message.setOneofField(this, 3, proto.grakn.protocol.Options.oneofGroups_[2], undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.grakn.protocol.Options.prototype.hasBatchSize = function() {
  return jspb.Message.getField(this, 3) != null;
};


goog.object.extend(exports, proto.grakn.protocol);
