load("//test:rules.bzl", "node_cucumber_test")

#node_cucumber_test(
#    name = "entity-test",
#    features = ["@graknlabs_behaviour//concept/thing:entity.feature"],
#    node_modules = "//:node_modules",
#    package_json = "//:package.json",
#    core_artifact = "@graknlabs_grakn_core_artifact_mac//file",
#    deps = ["//:client-nodejs"],
#    steps = [],
#)